name: Publish
on:
  push:
    branches:
      - release-cooed-router

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: |
          cd ws/cooed
          npx jsr publish
